### PR TITLE
Refactor PDF processor

### PR DESCRIPTION
**Pull request by anbuzin**
Decouple processing pipeline

- `MathpixProcessor` does interactions with Mathpix API
- `MathpixResult` extracts files from zip and processes them into a string

Extract helpers for processing latex such as chunker and regex tools into latex_helpers.py.

Remove database interactions and paper deduplication to reimplement them outside of the processing pipeline in the future.

### CODE REVIEW

**Review by kuldin — APPROVED** [review]
In future refactoring, it would be good to add docstrings to each helper function.

**Comment by zenssh** [comment]
Is the usage pattern like this?
1. when you get a paper call submit_pdf and get result immediately if you want to use it immediately
1*. await_result if you want to use it later and need to check that it was processed and fetch result
2. send result to parse_result

Wouldn't it be more logical instead of using singletons and manually passing results between their methods,
instead to have an object for each pdf that would hold pdf_path, pdf_id, mathpix_result, latex_chunks, pdf_result etc?
eg PDF(pdf_path)/PDFProcessor(pdf_path) that would have methods to:
1. send pdf to mathpix
2. wait/retrieve result from mathpix
3. parse latex into pdf/text
4? process text eg summarize, replace terms etc

Also you got rid of the database that prevented duplicate calls to mathpix, was it not necessary?

**Comment by anbuzin** [comment]
@kuldin right, I forgot to add those. Will do.

@zenssh 
1. Currently it goes like this:

- You submit a PDF and receive a `MathpixResult` object that holds the source path, `pdf_id` (if the upload was successful) and/or the error that came from the server. It won't actually raise the error though, so it's up to you if you want to deal with it.
- You call `await_result` and pass a `MathpixResult` with `pdf_id` to it (could be from a previous step, or made manually). It then reports processing status from the server, and downloads the `tex.zip` file when it's done. It then attaches that zip file to the original MathpixResult.
- You call a `MathpixResultParser.parse_output` and pass your `MathpixResult` with `pdf_id` and `zip_bytes`. It unpacks the zip and chunks the latex file. It assembles a new object of type `PdfResult` that contains the original latex, all of the chunks and the cleaned up final version of the output. 

2. I considered storing everything in the same structure, but settled on storing Mathpix-related stuff and LaTeX stuff separately. I think retaining a `pdf_id` in the `PdfResult` might be a good idea though.
3. I plan to add a convenience function to do the end-to-end processing, but I specifically wanted to make this workflow accessible. Seeing how we're shipping this to people none of whom plan to use it the same way we do, I feel like it's important to not impose one single order of doing stuff.
4. Things such as summarization and replacing terms belong in the index building part that's going to be downstream.
5. As mentioned, I think it doesn't really belong inside either of those classes. Deduplication needs to come before calling the Mathpix API anyway. I'm also in favor of replacing sqlite with a JSON file that users can read and edit it in plain text.

**Comment by zenssh** [comment]
I still don't understand what's the point of passing MathpixResult around and checking its state. 
You can have one object and call methods on it - If you have a raw pdf, you construct it with path and process with mathpix, if you have done some preprocessing, you construct it differently.
Anyway, let's finish all the steps so that we can assess how it would make sense to be used, and I'll make a PR with a refactor if it's necessary.

I agree, JSON would be better than a database, but we need some way to save pdf_id if we're making multiple calls to Mathpix
Actually, it would make sense to save zip file from MathpixResult locally, and then work with a local file. This way Mathpix would only be used once for processing, and then you don't need to store pdf_id after processing.
Also, if there another (eg free) way of parsing than Mathpix, we can swap it easily.

**Review by zenssh — APPROVED** [review]

**Pull request merged**
